name: pySpinW

on:
  push:
    branches: [pyspinw]
  workflow_dispatch:

jobs:
  compile_mex:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        matlab_version: [latest]
        include:
          - os: ubuntu-latest
            matlab_version: R2020a
          - os: macos-latest
            INSTALL_DEPS: brew install llvm libomp
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out SpinW
        uses: actions/checkout@v3
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1 # v1.1.0 required for Windows/MacOS support
        with:
          release: ${{ matrix.matlab_version }}
      - name: Remove old mex
        run: |
          ls
          cd ${{ github.workspace }}
          ls
          rm ./**/*.mex*
      - name: Run MEXing
        uses: matlab-actions/run-command@v1
        with:
          command: "addpath(genpath('external')); sw_mex('compile', true, 'test', false, 'swtest', false);"
      - name: Create TAR
        run: |
          cd ${{ github.workspace }}
          tar -cvf mex.tar ./**/*.mex*
      - name: Upload MEX results
        uses: actions/upload-artifact@v3
        with:
          name: MEX
          path: ${{ github.workspace }}/mex.tar
  build_ctfs:
    needs: compile_mex
    strategy:
      matrix:
        matlab_version: [R2021a, R2021b, R2022a, R2022b, R2023a]
    runs-on: self-hosted
    steps:
      - name: Check out SpinW
        uses: actions/checkout@v3
      - name: Download MEX artifacts
        uses: actions/download-artifact@v3
        with:
          name: MEX
          path: ${{ github.workspace }}
      - name: Extract MEX
        run: |
          ls
      - name: Build ctf
        run: |
          ls
          cd python
          /Applications/MATLAB_${{ matrix.matlab_version }}.app/bin/matlab -nodisplay -r "build_ctf; exit"
      - name: Upload CTF results
        uses: actions/upload-artifact@v3
        with:
          name: CTF
          path: ${{ github.workspace }}/python/ctf/*.ctf

  build_wheel:
    runs-on: ubuntu-latest
    needs: build_ctfs
    permissions:
      contents: write
    steps:
      - name: Checkout SpinW
        uses: actions/checkout@v3    
      - name: Download CTF artifacts
        uses: actions/download-artifact@v3
        with:
          name: CTF
          path: python/ctf
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
      - name: Move and build
        run: |
          cd python
          echo "PYSPINW_VERSION=$( cat pyproject.toml | grep "version = \"" | awk -F'"' '$0=$2' | sed 's/ //g' )" >> $GITHUB_ENV
          mkdir pyspinw/ctfs
          mv ctf/*.ctf pyspinw/ctfs
          python -m pip wheel --no-deps --wheel-dir build .
      - name: Create wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: pySpinW Wheel
          path: ${{ github.workspace }}/python/build/*.whl        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/python/build/*.whl
          prerelease: true
          replacesArtifacts: true
          name: "pySpinW"
          tag: ${{ env.PYSPINW_VERSION }}
          bodyFile: ${{ github.workspace }}/python/release_notes.md
