name: SpinW Tests

on:
  push:
    branches: [pyspinw]
  workflow_dispatch:

jobs:
  build_ctfs:
    strategy:
      matrix:
        matlab_version: [R2021a, R2021b, R2022a, R2022b, R2023a]
    runs-on: self-hosted
    steps:
      - name: Check out SpinW
        uses: actions/checkout@v3
      - name: Build ctf
        run: |
          ls
          cd python
          /Applications/MATLAB_${{ matrix.matlab_version }}.app/bin/matlab -nodisplay -r "build_ctf; exit"
      - name: Upload CTF results
        uses: actions/upload-artifact@v3
        with:
          name: CTF
          path: ${{ github.workspace }}/python/ctf/*.ctf

  build_wheel:
    runs-on: ubuntu-latest
    needs: build_ctfs
    permissions:
      contents: write
    steps:
      - name: Checkout SpinW
        uses: actions/checkout@v3    
      - name: Download CTF artifacts
        uses: actions/download-artifact@v3
        with:
          name: CTF
          path: python/ctf
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
            python-version: 3.8
      - name: Move and build
        run: |
          cd python
          mkdir pyspinw/ctfs
          mv ctf/*.ctf pyspinw/ctfs
          python -m pip wheel --no-deps --wheel-dir build .
      - name: Create wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: pySpinW Wheel
          path: ${{ github.workspace }}/python/build/*.whl        
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/python/build/*.whl
          prerelease: true
          replacesArtifacts: true
          name: "pySpinW"
          bodyFile: ${{ github.workspace }}/python/release_notes.md
